extends: airbnb
env:
  jasmine: true
rules:
  react/jsx-filename-extension: off
  react/forbid-prop-types: off
  max-len:
    - error
    - 140
    - 2
  arrow-parens:
    - error
    - as-needed
  new-cap:
    - error
    - capIsNewExceptions:
      - Immutable
      - Radium
