extends: airbnb
env:
  jasmine: true
plugins:
  - flowtype
rules:
  react/jsx-filename-extension: off
  react/forbid-prop-types: off
  max-len:
    - error
    - 120
    - 2
  arrow-parens:
    - error
    - as-needed
  new-cap:
    - error
    - capIsNewExceptions:
      - Immutable

  #require-parameter-type: warn
  #require-return-type: warn
  flowtype/space-after-type-colon: error
  flowtype/space-before-type-colon: error
