env:
  browser: true
  es6: true
  jasmine: true
extends: airbnb
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
    impliedStrict: true
  sourceType: module
plugins:
  - react
  - flowtype
rules:
  max-len:
    - error
    - 120
    - 2
  arrow-parens:
    - error
    - as-needed
  new-cap:
    - error
    - capIsNewExceptions:
      - Immutable

  #Flow:
  #require-parameter-type: warn
  #require-return-type: warn
  flowtype/space-after-type-colon: error
  flowtype/space-before-type-colon: error
